// One-time import script — run with: node scripts/seed-clients.js
const Database = require('better-sqlite3');
const path = require('path');

const DB_PATH = path.join(__dirname, '..', 'data', 'qcl.db');
const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');

let _c = 0;
function uid() { return (Date.now() + _c++).toString(36) + Math.random().toString(36).slice(2, 5); }

const ts = new Date().toLocaleString('en-GB', {
  day: '2-digit', month: 'short', year: '2-digit', hour: '2-digit', minute: '2-digit',
});

function n(text) {
  return { id: uid(), type: 'gen', text: text.trim(), ts };
}

const clients = [
  {
    name: 'John Dowling',
    email: '',
    va: '',
    start: "Jun '25",
    status: 'Stopped',
    li: 'Not Eligible (Appointment)',
    ert: '',
    ertTime: '',
    attendees: 1,
    registered: 0,
    flag: 'Very specific targeting',
    notes: [n('Specific targeting: heavy equipment manufacturing dealerships. Struggling from Day 1, Lisa is aware. Apr 28 meeting: agreed to use lead list of 700 dealerships from Sales Navigator. Added North America to targeting. OK to reach out to 1st degree connections (16k) — start with 700 dealership list first.')],
  },
  {
    name: 'Greg Barlage',
    email: '',
    va: 'Peevee',
    start: "Jul '25",
    status: 'At Risk',
    li: 'Active',
    ert: '2026-06-03',
    ertTime: '12:30 PM EST',
    attendees: 3,
    registered: 0,
    flag: '',
    notes: [n('Suggested shifting messaging and targeting to safety-related topics. Agreed to wait for next ERT result before changing strategy. Schedule next ERT after June 3.')],
  },
  {
    name: 'Dina Scippa',
    email: '',
    va: 'Rosalie',
    start: "Jul '25",
    status: 'Performing',
    li: 'Active',
    ert: '2026-05-28',
    ertTime: '',
    attendees: 31,
    registered: 0,
    flag: '',
    notes: [n('Meeting May 6th: may want to expand targeting to include VPs alongside HR after next ERT. Hughie asked to have Habiba join the call. Connection issues on March 26 ERT, asked for reschedule. ERT history: March 26 (no attendees / 10 reg), April 16 (2 att / 10 reg), May 14 (4/10 att).')],
  },
  {
    name: 'Marcus Brecheen',
    email: '',
    va: '',
    start: "Nov '25",
    status: 'Stopped',
    li: 'Active',
    ert: '',
    ertTime: '',
    attendees: 3,
    registered: 7,
    flag: '',
    notes: [n('March 24 ERT failed — Zoom link was invalid, registered people couldn\'t join. As compensation: free Roundtable Scripting and Proposal Bots. Changed LinkedIn password so we\'re unable to log in. Waiting for confirmation to proceed with campaign.')],
  },
  {
    name: 'Torsten Borchers (P2P)',
    email: 'torsten@cidesignconsulting.com',
    va: 'Rosalie',
    start: "Jun '25",
    status: 'Slow Generating',
    li: 'Active',
    ert: '2026-05-28',
    ertTime: '10am CT',
    attendees: 28,
    registered: 2,
    flag: '',
    notes: [n('April 16 ERT cancelled by Torsten — did not reply to reschedule email. Had 2 registered for that cancelled ERT, reached out to them to join next ERT or book 1-on-1 appointment. Total attendees include 13 appointments. Last ERT May 7: 2 attendees.')],
  },
  {
    name: 'Jason D. Hurt',
    email: '',
    va: '',
    start: "Dec '25",
    status: 'Stopped',
    li: 'Not Eligible (Appointment)',
    ert: '',
    ertTime: '',
    attendees: 1,
    registered: 0,
    flag: '',
    notes: [n('Shifting to email campaign. March 10 meeting: agreed Jason reviews lead list first, then VA starts sending messages. Sent email asking for new company email for email campaign.')],
  },
  {
    name: 'Mike Brown Jr.',
    email: 'mike@theleadervibe.com',
    va: 'Peevee',
    start: "Feb '25",
    status: 'Slow Generating',
    li: 'Active',
    ert: '',
    ertTime: '',
    attendees: 0,
    registered: 0,
    flag: 'Started on RedZone 5 May',
    notes: [n('Met April 29. May 26 ERT postponed to June as not enough registered leads. Proposed new message pending approval. Subscribed to RedZone. Last attempted ERT: May 26 at 1pm CST — 0/7 registered.')],
  },
  {
    name: 'Jason Lockhart',
    email: 'jason@kitchenandbathmarketingsolutions.com',
    va: 'Peevee',
    start: "Mar '25",
    status: 'New Client',
    li: 'Check',
    ert: '2026-06-09',
    ertTime: '11am CST',
    attendees: 0,
    registered: 0,
    flag: 'Started on RedZone 5 May',
    notes: [n('Started outreach on RedZone 5/5/26. Previous ERTs: May 12 at 11am CST and May 26 at 11am CT — no attendees on both.')],
  },
  {
    name: 'Peter Yaholkovsky',
    email: 'peter.yaholkovsky@gmail.com',
    va: 'Lyrah',
    start: "Mar '25",
    status: 'Slow Generating',
    li: 'Active',
    ert: '2026-05-27',
    ertTime: '12 PM EST',
    attendees: 1,
    registered: 0,
    flag: '',
    notes: [n('Will subscribe to $59.99 plan. Payment link sent after April 15 meeting. Sales Navigator subscription ended May 10. Schedule next ERT after May 27. ERTs: April 16 (1 att), May 6 (2/2 att).')],
  },
  {
    name: 'Deron McCoy',
    email: 'Dmccoy@investatewealth.com',
    va: 'Mary',
    start: "Feb '25",
    status: 'New Client',
    li: 'Active',
    ert: '',
    ertTime: '',
    attendees: 2,
    registered: 0,
    flag: '',
    notes: [n('Met April 2. Scheduled first ERT April 29. Waiting for zoom link, calendar link, and banner approval. ERTs: April 29 (0/4 att), May 14 (2/6 att).')],
  },
  {
    name: 'COL. Tom Hegna',
    email: '',
    va: 'Mary',
    start: "Mar '25",
    status: 'New Client',
    li: '',
    ert: '',
    ertTime: '',
    attendees: 0,
    registered: 0,
    flag: '',
    notes: [n('Messaging and targeting not approved yet. Setting up for appointments until April 25, then shift back to ERT. PGL meeting needed week of March 22.')],
  },
  {
    name: 'Brian Hardy',
    email: 'bhardy@whiteoak-consulting.com',
    va: '',
    start: "Nov '25",
    status: 'Stopped',
    li: 'Active',
    ert: '',
    ertTime: '',
    attendees: 2,
    registered: 14,
    flag: '',
    notes: [n('March 11 ERT: 14 registered, 0 attendees. March 25 ERT also scheduled. Lisa posted on MCL to stop outreach on his account.')],
  },
  {
    name: 'Don Durand / Kari Zeller',
    email: 'LJoiner@tgn.llc',
    va: 'Arvi',
    start: "Oct '25",
    status: 'At Risk',
    li: 'Inactive',
    ert: '',
    ertTime: '',
    attendees: 4,
    registered: 0,
    flag: 'Waiting to approve lead list',
    notes: [n('Meeting with Lindsey March 10: target companies with >1k employees, revenue $500M–$1B. Waiting to approve current lead list before starting new one. April 28 ERT was cancelled. March 5 ERT was also cancelled.')],
  },
  {
    name: 'Anthony Franco',
    email: 'anthony@francoinc.com',
    va: 'Arvi',
    start: "Jan '25",
    status: 'Performing',
    li: 'Active',
    ert: '',
    ertTime: '',
    attendees: 17,
    registered: 10,
    flag: '',
    notes: [n('Schedule next ERT. Create LI events banner. OK with 1-on-1 appointments for leads unable to join ERT. Waiting for logo. Increase headcount targeting: 10–50 and 50–100. Website: wisermethod.com. He said he is OK to schedule 1-on-1 for leads that didn\'t attend. Last ERT May 14: 10/10 attendees.')],
  },
  {
    name: 'Jon Kidwell',
    email: 'jon@leadwell.com',
    va: 'Mary',
    start: "Mar '26",
    status: 'New Client',
    li: '',
    ert: '',
    ertTime: '',
    attendees: 0,
    registered: 0,
    flag: '',
    notes: [n('Reach out to Aubrey when we reach 5 interested leads to schedule first ERT and create LI events banner. Not available until after May 15th.')],
  },
  {
    name: 'Robert W. Looper',
    email: 'RLooper@LooperGrp.com',
    va: 'Mary',
    start: "Mar '26",
    status: 'New Client',
    li: '',
    ert: '',
    ertTime: '',
    attendees: 0,
    registered: 0,
    flag: 'Read notes before next meeting',
    notes: [n('PGL on April 16th. Targeting and messaging approved. Wants someone from his sales team to join before confirming first ERT date and zoom link. POC is also Craig Outland: COutland@loopergrp.com.')],
  },
  {
    name: 'Nigel Long',
    email: 'Nigel.long@kingfishercloudconsulting.com',
    va: 'Mary',
    start: "Dec '25",
    status: 'At Risk',
    li: 'Active',
    ert: '2026-06-08',
    ertTime: '2:00 PM EST',
    attendees: 9,
    registered: 0,
    flag: '',
    notes: [n('Annual subscription, renewal Jan 26. Good volume of interested leads but not converting to registered/attended. Need to check how many LI invites sent and the invitation message. Check follow-ups before last ERT. ERTs: March 25 (2/3 att), April 22 (3/10 att), May 13 (3/7 att).')],
  },
  {
    name: 'Carol Schultz',
    email: 'carol@verticalelevation.com',
    va: 'Mary',
    start: "Jun '24",
    status: 'Performing',
    li: 'Not Eligible (Appointment)',
    ert: '',
    ertTime: '',
    attendees: 28,
    registered: 0,
    flag: '',
    notes: [n('Wants to pause ERTs as not getting attendees. Some messages not responded to by VA. Wants to pivot to podcast outreach. Sales Navigator ended April 19, subscribed to RedZone April 20. Confirm if we can remove previous cancelled LI events. Last ERT March 12: 0 attendees.')],
  },
  {
    name: 'Jarrod Aldom',
    email: 'jarrod.aldom@gmail.com',
    va: 'Mary',
    start: "Jan '26",
    status: 'Slow Generating',
    li: 'Active',
    ert: '',
    ertTime: '',
    attendees: 7,
    registered: 0,
    flag: '',
    notes: [n('Met April 10. Agreed to apply small edits to targeting, posted on MCL. Should send proposed message and banner. ERTs: March 26 (2/4 att), April 9 (cancelled). Got 5 attendees on March 12 ERT — promising.')],
  },
  {
    name: "CAT GLORIA (Carol Schultz's 2nd acc)",
    email: '',
    va: 'Mary',
    start: '',
    status: 'Stopped',
    li: '',
    ert: '',
    ertTime: '',
    attendees: 0,
    registered: 0,
    flag: '',
    notes: [n('Client cancelling Sales Navigator for this account. Will only work on Carol\'s main account going forward.')],
  },
  {
    name: 'Katherine Snyder',
    email: 'kldconsulting@charter.net',
    va: 'Mary',
    start: "Feb '25",
    status: 'New Client',
    li: 'Active',
    ert: '2026-05-28',
    ertTime: '',
    attendees: 0,
    registered: 0,
    flag: '',
    notes: [n('Pending: Zoom link, Calendar link, Script, Banner creation, Schedule next ERT. Last ERT May 7: 4/8 attendees.')],
  },
  {
    name: 'Marko Baric',
    email: 'marko@electricwebmarketing.com',
    va: 'Arvi',
    start: "Nov '25",
    status: 'Stopped',
    li: 'Active',
    ert: '',
    ertTime: '',
    attendees: 8,
    registered: 0,
    flag: 'Paused — waiting for RedZone subscription',
    notes: [n('Campaign paused. Does not want outreach on Sales Navigator until he subscribes to RedZone ($120 plan). Met Elie and Marko with Lisa. ERTs: March 24 (4 att), April 14 (1 att).')],
  },
  {
    name: 'Rajshree Sharma (Cybersecurity)',
    email: 'Rajshree@Vidyatech.com',
    va: 'Arvi',
    start: "May '25",
    status: 'At Risk',
    li: 'Active',
    ert: '',
    ertTime: '',
    attendees: 12,
    registered: 0,
    flag: '',
    notes: [n('Subscribed to annual plan April 4 — not interested in RedZone. Proposed new messaging & banner pending. Check if LinkedIn account changes were made. ERTs: March 26 (cancelled), April 16 (0 att), April 30 (1/1 att). Contacts: Bivin@vidyatech.com, satishnair@vidyatech.com')],
  },
  {
    name: 'Rajshree Sharma (Tech Learning)',
    email: 'Rajshree@Vidyatech.com',
    va: 'Arvi',
    start: "Apr '26",
    status: 'New Client',
    li: '',
    ert: '',
    ertTime: '',
    attendees: 0,
    registered: 0,
    flag: '',
    notes: [n('Soft launch. Second account for Rajshree Sharma (separate from Cybersecurity account).')],
  },
  {
    name: 'Stella Likhterman (P2P)',
    email: 'Stellalik20@gmail.com',
    va: 'Arvi',
    start: "Apr '24",
    status: 'Performing',
    li: 'Active',
    ert: '2026-05-27',
    ertTime: '11am CT',
    attendees: 39,
    registered: 0,
    flag: 'Started on RedZone 5 May',
    notes: [n('P2P. ERTs: March 25 (4/10 att), April 22 (5/14 att), May 27 at 11am CT.')],
  },
  {
    name: 'Jane Hundley',
    email: 'jane@impactmanagementusa.com',
    va: 'Arvi',
    start: "Jun '22",
    status: 'Performing',
    li: 'Not Eligible (Appointment)',
    ert: '',
    ertTime: '',
    attendees: 178,
    registered: 0,
    flag: 'Started on RedZone 5 May',
    notes: [n('Subscribed to $65 Bronze Plan. Total: 178 ERT attendees and 139 appointments.')],
  },
  {
    name: 'Kim Groshek (P2P)',
    email: 'kim.groshek@gmail.com',
    va: 'Arvi',
    start: "Sep '25",
    status: 'Performing',
    li: 'Active',
    ert: '',
    ertTime: '',
    attendees: 49,
    registered: 0,
    flag: 'Do not work on campaign until Nahla confirms P2P',
    notes: [n('P2P. Last 2 ERTs she kicked Arvi out and is completely unresponsive — does not reply to emails or calls from Hughie. Do not work on campaign until Nahla meets with Kim and confirms P2P status.')],
  },
  {
    name: 'Brian Keltner',
    email: 'briankeltner1@gmail.com',
    va: 'Arvi',
    start: "Jan '25",
    status: 'Performing',
    li: 'Active',
    ert: '2026-05-27',
    ertTime: '',
    attendees: 10,
    registered: 0,
    flag: '',
    notes: [n('Slowly performing as not using LI events. ERTs: March 3 (3/3), March 18 (2/4), March 31 (3/8), April 8 (1/7), April 16 (1/2), April 29 (none), May 13 (none), May 27.')],
  },
  {
    name: 'Francesca Kenney',
    email: 'francesca@francescakenney.com',
    va: 'Arvi',
    start: "Jan '25",
    status: 'Performing',
    li: 'Active',
    ert: '2026-06-02',
    ertTime: '',
    attendees: 12,
    registered: 0,
    flag: '',
    notes: [n('Slowly performing as not using LI events. ERTs: March 3 (1/3), March 26 (5/8), April 9 (1/3), April 20 (1/2), May 12 (none), June 2 next.')],
  },
  {
    name: 'Bryson McCall',
    email: 'Bryson@eminenthrgroup.com',
    va: '',
    start: "May '25",
    status: 'New Client',
    li: '',
    ert: '',
    ertTime: '',
    attendees: 0,
    registered: 0,
    flag: 'on RedZone',
    notes: [n('Waiting for approved message and targeting. Started May 8.')],
  },
];

// Clear existing clients
db.prepare('DELETE FROM clients').run();
console.log('Cleared existing clients.');

const stmt = db.prepare(`
  INSERT INTO clients (id, name, email, va, start, status, li, ert, ert_time, attendees, registered, message, targeting, flag, notes, sort_order)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const insertAll = db.transaction((list) => {
  list.forEach((c, i) => {
    stmt.run(
      uid(), c.name, c.email || '', c.va || '', c.start || '',
      c.status || 'New Client', c.li || '', c.ert || '', c.ertTime || '',
      c.attendees || 0, c.registered || 0, '', '',
      c.flag || '', JSON.stringify(c.notes || []), i
    );
  });
});

insertAll(clients);
console.log(`Inserted ${clients.length} clients successfully.`);
db.close();
